[general]
live_config_reload = true


[window]
opacity = 0.7

padding.x = 10
padding.y = 10

decorations = "None"

[font]

normal.family = "Hack"
bold.family = "Hack"
italic.family = "Hack"
bold_italic.family = "Hack"

size = 11.0

[cursor] 
style = "Beam"
thickness = 0.1

unfocused_hollow = true
